### ISSUE TITLE
panlex_lite.xml causes build failure

### ISSUE THREAD

**Issue by yooper** [nltk/nltk_data#57]
Trying to build index.xml, but I keep getting this error. Any suggestions?  

```
$ python tools/build_pkg_index.py . https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/packages index.xml
Traceback (most recent call last):
  File "C:\Users\XXX\Anaconda3\lib\site-packages\nltk\downloader.py", line 2200, in _find_packages
    try: zf = zipfile.ZipFile(zipfilename)
  File "C:\Users\XXX\Anaconda3\lib\zipfile.py", line 1009, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: '.\\packages\\corpora\\panlex_lite.zip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tools/build_pkg_index.py", line 24, in <module>
    index = build_index(ROOT, BASE_URL)
  File "C:\Users\XXX\Anaconda3\lib\site-packages\nltk\downloader.py", line 2085, in build_index
    for pkg_xml, zf, subdir in _find_packages(os.path.join(root, 'packages')):
  File "C:\Users\XXX\Anaconda3\lib\site-packages\nltk\downloader.py", line 2203, in _find_packages
    (zipfilename, e))
ValueError: Error reading file '.\\packages\\corpora\\panlex_lite.zip'!
[Errno 2] No such file or directory: '.\\packages\\corpora\\panlex_lite.zip'

```

```
>>> import nltk;
>>> print('The nltk version is {}.'.format(nltk.__version__))
The nltk version is 3.2.1.
```

**Comment by alvations** [comment]
First download the `panlex_lite.zip` file using the normal `nltk.downloader`:

```
python -m nltk.downloader panlex_lite
```

Then move the panlex_lit.zip in your `nltk_data` directory into the repo where you want to run the MakeFile that runs `tools/build_pkg_index.py`

**Comment by stevenbird** [comment]
I have removed Panlex_lite from the NLTK data distribution until we find a better solution. In the meantime, anyone wanting to use it will need to manually download [the latest panlex snapshot](https://db.panlex.org/panlex_lite.zip), unpack it into `$NLTK_DATA/corpora/panlex_lite`, then access the [panlex_lite corpus reader](https://github.com/nltk/nltk/blob/develop/nltk/corpus/__init__.py#L166) using `from nltk.corpus import panlex_lite` in the usual way.
